#==================================================
# This file configures the RabbitMQ server cluster
#  and inbound traffic HAProxy
#==================================================

meta:
  rabbitmq_tls:
    key:    (( vault meta.vault "/rabbitmq/certs/server:key" ))
    cert:   (( vault meta.vault "/rabbitmq/certs/server:certificate" ))
    cacert: (( vault meta.vault "/rabbitmq/certs/ca:certificate" ))

  mgmt_tls:
    key:    (( vault meta.vault "/mgmt/certs/server:key" ))
    cert:   (( vault meta.vault "/mgmt/certs/server:certificate" ))
    cacert: (( vault meta.vault "/mgmt/certs/ca:certificate" ))

  mgmt_port: 15671

params:
  rmq_domain: (( param "Please specify the domain of the RabbitMQ loadbalancer" ))
  check_queue_sync: false

instance_groups:
- name: rmq-server
  instances: (( grab params.rmq_instances || 3 ))
  jobs:
  - name: rabbitmq-server
    release: cf-rabbitmq
    properties:
      rabbitmq-server:
        version: "3.8"
        plugins:
        - rabbitmq_management
        ports:
        - 5672 #AMQP
        - 5671 #AMQPS
        - 15671 #RMQ Management TLS
        - 15672 #RMQ Management
        administrators:
          management:
            username: management
            password: (( vault meta.vault "/rabbitmq/admin/management:password" ))
          broker:
            username: broker
            password: (( vault meta.vault "/rabbitmq/admin/broker:password" ))
        cookie: (( vault meta.vault "/rabbitmq/erlang-cookie:cookie" ))
        cluster_partition_handling: pause_minority
        ssl:
          enabled: true
          key:    (( grab meta.rabbitmq_tls.key ))
          cert:   (( grab meta.rabbitmq_tls.cert ))
          cacert: (( grab meta.rabbitmq_tls.cacert ))
          versions:
          - tlsv1.2
          # Verification is off because we don't currently have a way to
          # automagically sign the certificate for the IPs that the servers
          # will be dynamically assigned.
          verify:                    false
          verification_depth:        5
          fail_if_no_peer_cert:      false
        check_queue_sync: (( grab params.check_queue_sync ))
        management_tls:
          enabled: true
          cacert: (( grab meta.mgmt_tls.cacert ))
          cert:   (( grab meta.mgmt_tls.cert ))
          key:    (( grab meta.mgmt_tls.key ))

  vm_type: (( grab params.server_vm_type || "rabbitmq" ))
  stemcell: default
  persistent_disk_type: (( grab params.server_disk_type || "rabbitmq" ))
  networks:
  - name: (( grab params.server_network || "rabbitmq" ))
  azs: (( grab params.availability_zones || meta.default.azs ))

- name: haproxy
  instances: 1
  jobs:
  - name: rabbitmq-haproxy
    release: cf-rabbitmq
  - name: bpm
    release: bpm
  vm_type: (( grab params.proxy_vm_type || "small" ))
  stemcell: default
  networks:
  - name: (( grab params.proxy_network || "rabbitmq" ))
    static_ips: (( static_ips 0 ))
  azs: (( grab params.availability_zones || meta.default.azs ))

releases:
- name: cf-rabbitmq
  .:    (( inject meta.releases.cf-rabbitmq ))
- name: bpm
  .:    (( inject meta.releases.bpm ))

exodus:
  management_url: (( concat "https://" params.rmq_domain ":" meta.mgmt_port ))
  management_username: (( grab instance_groups.rmq-server.jobs.rabbitmq-server.properties.rabbitmq-server.administrators.management.username ))
  management_password: (( grab instance_groups.rmq-server.jobs.rabbitmq-server.properties.rabbitmq-server.administrators.management.password ))
